---
output: 
  pdf_document:
    pandoc_args: [
      "-V", "classoption=twocolumn"
    ]
---

# \textit{Bootstrap sampling is comparable to continued sampling of a population of a known distribution.}

Parker Hicks,
HMGGP PhD Student

## Abstract
In many cases, sampling an entire population to elucidate the true value for a given statistic is unfeasible. Bootstrap sampling offers a solution by estimating the distribution of a statistic based on a single sample. This study tests the comparability between bootstrap-sampled distributions and those obtained through continuous sampling of populations with known distributions. Here, we show that these two methods are comparable, further affirming that bootstrap sampling provides comparable results to continued sampling from a population with a known underlying distribution. This validation underscores the utility of bootstrap techniques in approximating true population statistics, offering a practical and reliable alternative in scenarios where complete population sampling is unattainable.

Publicly-available and reproducible code for these simulations is available at <https://github.com/phicks22/BIOS-6611-midterm>.

\textit{Keywords:} boostrap, population sampling, PRS

## Introduction


## Motivating Problem


## Simulation Set-up


## Results

\setlength{\headheight}{22.48878pt}
\setlength{\topmargin}{-12pt}
\begin{table}[h]
\centering
\begin{tabular}{|l|l|l|}
\hline
\multicolumn{3} { | c | }{\textbf{Table 1:} Distribution summary statistics}\\ \hline
\textit{Statistic} & \textbf{Cont. Samp.} & \textbf{Boostrap} \\ \hline
$\mu$    & 1.0  & 0.96 \\ \hline
$SE$      & 0.058 & 0.041 \\ \hline
$\sigma^2$ & 0.003 & 0.003 \\ \hline
$Bias$    & - & -0.036 \\ \hline
\end{tabular}
\end{table}

## Conclusion


## References
